version: "3"
services:
  blog:
    container_name: blog
    build:
      context: ./apps/blog
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./apps/blog:/app
  admin:
    container_name: admin
    build:
      context: ./apps/admin
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./apps/admin:/app
  api:
    container_name: api
    build:
      context: ./apps/api
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./apps/api:/app
  database:
    container_name: database
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
  migrations:
    container_name: migrations
    build:
      context: ./migrations
    environment:
      - PGDATABASE=kuchnia_na_obcasach
      - PGUSER=root
      - PGPASSWORD=root
      - PGHOST=database
    depends_on:
      - database
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - blog
      - admin
      - api
      - database
      - migrations

